services:
  web:
    platform: linux/amd64
    image: mahediali072/django-app:latest
    container_name: django-app
    restart: always
    expose:
      - "80:8000"
    volumes:
      - sqlite_data:/app/data
      - static_volume:/app/static  # Shared static folder

volumes:
  sqlite_data:
  static_volume: # Define the shared volume