services:
  web:
    platform: linux/amd64
    image: mahediali072/django-app:latest
    container_name: django-app
    restart: always
    ports:
      - "80:8000"  # expose directly
    volumes:
      - sqlite_data:/app/data
      - static_volume:/app/static

volumes:
  sqlite_data:
  static_volume: