services:
  web:
    platform: linux/amd64
    image: mahediali072/django-app:latest
    container_name: django-app
    restart: always
    expose:
      - "8000"
    volumes:
      - sqlite_data:/app/data
      - static_volume:/app/static

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - static_volume:/app/static:ro
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - web

volumes:
  sqlite_data:
  static_volume: