services:
  web:
    platform: linux/amd64
    image: mahediali072/django-app:latest
    container_name: django-app
    restart: always
    ports:
      - "80:8000"
      - "443:8000"
    volumes:
      - sqlite_data:/app/data
      - static_volume:/app/static
      - /etc/letsencrypt:/etc/letsencrypt:ro

volumes:
  sqlite_data:
  static_volume: